language: python
python:
  - "2.7"
before_install:
 - "sudo apt-get update"
 - "sudo apt-get install libevent-dev"
install:
  - "pip install ."
  - "pip install -r tools/pip-requires --use-mirrors"
  - "pip install -r tools/test-requires --use-mirrors"
script:
  - "nosetests"
  - "pep8 curryproxy"
