dist: bionic
sudo: false
language: python
python:
  - 2.7
before_install:
  - sudo apt-get update
  - sudo apt-get install libevent-dev # Why?
  - pip install tox-travis
script:
  # Travis appears to ignore the envlist set in tox.ini, so we have to
  # specify the lint env here.
  - tox -e py27,lint
